<link rel="stylesheet" href="/ledelice/public/css/Accueil.css">

<div class="container">
<div class="base" id="accueil">
    <div class="title">
        <span class="nom"> Benvenuto a il Trattamento</span>
            
    </div>
</div>

<div class="apropos">
    <span id="apropostitle">l'Authenticité Culinaire Italienne</span>
    <p id="apropostext">Plongez dans un voyage gustatif au cœur de l'Italie à il Trattamento, où la passion pour la cuisine authentique italienne se mêle à une ambiance chaleureuse et accueillante.
         Notre restaurant est bien plus qu'un simple lieu pour savourer des plats italiens ; c'est une expérience culinaire immersive qui capture l'essence même de l'Italie.</p>
</div>
</div>