<link rel="stylesheet" href="/ledelice/public/css/ModifMenu.css">

<div class="container">
        <div class="form-container ">
                <form method="POST" action="/ledelice/admin/updateMenu/<?= $menu['id']; ?>">
                        <span>Modifier le plat</span>
                        <label for="titre">Titre :</label>
                        <input type="text" name="titre" value="<?php echo $menu['titre']; ?>"><br>

                        <label for="contenu">Contenu :</label>
                        <input type="text" name="contenu" value="<?php echo $menu['contenu']; ?>"><br>

                        <label for="prix">Prix :</label>
                        <input type="text" name="prix" value="<?php echo $menu['prix']; ?>"><br>

                        <label for="titre">Catégorie :</label>
                        <select name="categorie" >
                                <option><?php echo $menu['categorie']; ?></option>
                                <option>ANTIPASTI / À PARTAGER</option>
                                <option>INSALATA</option>
                                <option>PASTA</option>
                                <option>PIZZA</option>
                                <option>PESCE</option>
                                <option>RISOTTO</option>
                                <option>CARNE</option>
                                <option>DOLCI DELLA CASA</option>
                                <option>GELATO </option>
                                <option>COCKTAILS</option>
                        </select>

                        <button type="submit" id="valider" name="valider">Submit</button>


                </form>
        </div>
</div>

