<link rel="stylesheet" href="/ledelice/public/css/SignAdmin.css">

<div class="container" id="container">
<div class="form-container sign-up-container">
		<form method="POST" action="/ledelice/admin/signinAdmin">
			<span>Crée un compte admin</span>
			<input type="text" name="nom" placeholder="Nom" />
      		<input type="text" name="prenom" placeholder="Prénom" />
			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="mdp" placeholder="Mot de passe" />
			<button type="submit" name="valider">Crée</button>
		</form>
	</div>
  </div>